### ISSUE TITLE
No issue, just a thank you!

### ISSUE THREAD

**Issue by euterklaas** [zlaxy/sshch#7]
Just wanted to leave a short "thank you" for your work! Most of the time I'm a terminal-only user and using sshch at work helps so much with managing ssh connections. No need to fiddle around with aliases anymore. Plus a decent overview of all my configured connections. Thank you!

**Comment by zlaxy** [comment]
Nice to hear this. Thank you for the kind words, @euterklaas 
But everything you said, also applies to all contributors of this project: @Difrex, @jeff-99 and especially @GHPS
