### ISSUE TITLE
` character in password causes error

### ISSUE THREAD

**Issue by mplinuxgeek** [zlaxy/sshch#9]
Returns below error if password includes ` character:

```
/bin/sh: -c: line 0: unexpected EOF while looking for matching ``'
/bin/sh: -c: line 1: syntax error: unexpected end of file
```

**Comment by zlaxy** [comment]
@mplinuxgeek Hello, this repository was moved to: https://gitlab.com/zlax/sshch
Also, i made commit with fix: https://gitlab.com/zlax/sshch/commit/a39cd7ae684903ef7b54329cb75f29481d2f5890#f48a8759231e000660b4ebcd489bb369bcf57d4f
You can download latest version of this script there: https://gitlab.com/zlax/sshch/-/archive/master/sshch-master.tar.gz

I tested passwords with this special symbols: `"` `'` `\` `;` - all works fine.
Please test your passwords with updated version from gitlab, if everything will be ok - please close this issue.

**Comment by zlaxy** [comment]
@mplinuxgeek with this fix you need to update your passwords in sshch.conf (set passwords for aliases again)
